# Numpy
### relatively less memory to store data
### **efficiant storage**

In [1]:
import numpy as np

In [2]:
myarr = np.array([[3,4,57,99]], np.int32)

***for 2D array***

In [3]:
myarr[0,1]

4

In [4]:
myarr.shape

(1, 4)

In [5]:
myarr.dtype

dtype('int32')

***To change element in array***

In [6]:
myarr[0,1] = 80

In [7]:
myarr

array([[ 3, 80, 57, 99]])

# ***There are 6 general mechanisms for creating arrays:***

**1.Conversion from other Python structures (i.e. lists and tuples)**

In [8]:
listarray = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [9]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
listarray.dtype

dtype('int32')

# 2.Intrinsic NumPy array creation functions (e.g. arange, ones, zeros, etc.)

In [11]:
zeros = np.zeros((2, 4))

In [12]:
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

***create an arrray***

In [13]:
rng = np.arange(15)

In [14]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

***create equally linearly space array***

In [15]:
lspace = np.linspace(1,6,10)

In [16]:
lspace

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [17]:
emp = np.empty((4,6))

In [18]:
emp

array([[ 1.84368011e-004,  9.14678311e+135,  1.82962748e-307,
         4.40039742e+199,  3.86539254e+228,  7.44454207e+194],
       [ 6.96407467e+252, -5.31527558e-310,  2.04086401e+161,
         7.09627790e-283,  2.49731984e-307,  1.91192074e+214],
       [ 1.94520717e+188,  4.78627552e+101,  7.31576876e+223,
         1.70075256e+166,  1.08649313e-287,  2.04031484e+161],
       [ 7.54115956e-312,  2.71615461e-311,  3.63964718e-310,
         5.83289762e-302,  1.78092419e-306,  7.26670436e-292]])

In [19]:
emp_like = np.empty_like(lspace)

In [20]:
emp_like

array([1.        , 1.55555556, 2.11111111, 2.66666667, 3.22222222,
       3.77777778, 4.33333333, 4.88888889, 5.44444444, 6.        ])

In [21]:
ide = np.identity(45)

In [22]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [23]:
ide.shape

(45, 45)

In [24]:
arr = np.arange(99)

In [25]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [26]:
arr.reshape(3, 33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [27]:
arr = arr.ravel()

In [28]:
arr.shape

(99,)

In [29]:
x = [[1,2,3],[4,5,6],[7,8,9]]

In [30]:
ar = np.array(x)

In [31]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
ar.sum(axis=0)

array([12, 15, 18])

In [33]:
ar.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [34]:
ar.flat

In [35]:
for item in ar.flat:
    print(item)

1
2
3
4
5
6
7
8
9


In [36]:
ar.ndim

2

In [37]:
ar.size

9

***total bytes consumed***

In [38]:
ar.nbytes

36

In [39]:
one = np.array([1,2,33,4,5,9])

***gives max/min element index***

In [40]:
one.argmax()

2

In [41]:
one.argmin()

0

***how our indeses are so our array will be sorted***

In [42]:
one.argsort()

array([0, 1, 3, 4, 5, 2], dtype=int64)

In [43]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [44]:
ar.argmin()

0

In [45]:
ar.argmax()

8

In [46]:
ar.argmax(axis=0)

array([2, 2, 2], dtype=int64)

In [47]:
ar.argmax(axis=1)

array([2, 2, 2], dtype=int64)

In [48]:
ar.argsort(axis=1)

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [49]:
ar.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
ar.reshape((9,1))

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [51]:
ar2 = np.array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [52]:
ar + ar2

array([[ 1,  3,  5],
       [ 4,  6,  8],
       [ 7,  9, 11]])

In [53]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
ar2

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [55]:
ar*ar2

array([[ 0,  2,  6],
       [ 0,  5, 12],
       [ 0,  8, 18]])

In [56]:
np.sqrt(ar)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [57]:
ar.sum()

45

In [58]:
ar.max()

9

In [59]:
ar.min()

1

In [60]:
ar

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
np.where(ar>5)

(array([1, 2, 2, 2], dtype=int64), array([2, 0, 1, 2], dtype=int64))

In [64]:
type(np.where(ar>5))

tuple

In [65]:
np.count_nonzero(ar)

9

In [67]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 2, 0, 1, 2], dtype=int64))

In [68]:
ar[1,2] = 0

In [69]:
np.nonzero(ar)

(array([0, 0, 0, 1, 1, 2, 2, 2], dtype=int64),
 array([0, 1, 2, 0, 1, 0, 1, 2], dtype=int64))

In [70]:
import sys

In [72]:
py_ar = [0,4,55,2]

In [73]:
np_ar = np.array(py_ar)

In [74]:
sys.getsizeof(1) * len(py_ar)

112

In [75]:
np_ar.itemsize * np_ar.size

16

In [76]:
np_ar.tolist()

[0, 4, 55, 2]